### ISSUE TITLE
Sprites of objects appear where they're not supposed to.

### ISSUE THREAD

**Issue by LugiNess** [heyjoeway/sonic-wide-autopatcher#2]
I patched my Steam Sonic 2 rom and a few rom hacks, but when I started playing the graphics became a bit messed up. objects's sprites appeared were they aren't usually and when going past rings, they disappeared. going back to the rings I missed seemed to make them collectable again. The object sprites appearing and uncollectable rings are kind of a major issue. Even the level graphics glitch out, not palettes or anything like that, but the levels sprites sometimes appear where they're not supposed to be. This applied to every game, Sonic 2, Sonic Boom, Sonic Classic Heroes and Pana Sonic.

**Comment by heyjoeway** [comment]
Are you using this emulator? https://github.com/libretro/Genesis-Plus-GX-Wide

**Comment by heyjoeway** [comment]
Yeah, I can't reproduce this with the nightly build of that core. If you're not using that emulator then it's going to cause issues.

**Comment by LugiNess** [comment]
So I played it again today and it works fine now. Sorry for the late response.
